import type { Metadata } from "next";
import { Suspense } from "react";
import { APP_URL, APP_NAME, APP_DESCRIPTION } from "~/lib/constants";
import { getMiniAppEmbedMetadata } from "~/lib/utils";
import { SharePageClient } from "./SharePageClient";
export const revalidate = 300;

// This is an example of how to generate a dynamically generated share page based on fid:
// Sharing this route e.g. example.com/share/123 will generate a share page for fid 123,
// with the image dynamically generated by the opengraph-image API route.
export async function generateMetadata({
  params,
  searchParams,
}: {
  params: Promise<{ fid: string }>;
  searchParams: Promise<{ design?: string }>;
}): Promise<Metadata> {
  const { fid } = await params;
  const { design = 'orange' } = await searchParams;
  const imageUrl = `${APP_URL}/api/opengraph-image?fid=${fid}&design=${design}`;

  return {
    title: `${APP_NAME} - Share`,
    description: APP_DESCRIPTION,
    openGraph: {
      title: APP_NAME,
      description: APP_DESCRIPTION,
      images: [
        {
          url: imageUrl,
          width: 1200,
          height: 630,
          alt: 'Neynar Score',
        },
      ],
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title: APP_NAME,
      description: APP_DESCRIPTION,
      images: [imageUrl],
    },
    other: {
      "fc:frame": JSON.stringify(getMiniAppEmbedMetadata(imageUrl)),
    },
  };
}

export default async function SharePage({
  params,
  searchParams: _searchParams,
}: {
  params: Promise<{ fid: string }>;
  searchParams: Promise<{ design?: string }>;
}) {
  const { fid } = await params;
  return (
    <Suspense fallback={<div className="min-h-screen flex items-center justify-center">Loading...</div>}>
      <SharePageClient fid={Number(fid)} />
    </Suspense>
  );
}
